# Generated by Django 6.0.3 on 2026-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteCommerciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_dept', models.CharField(default='00', max_length=3)),
                ('bv2022', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=100)),
                ('ca_tot', models.FloatField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
            ],
            options={
                'unique_together': {('ville', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='MeteoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('jour', models.IntegerField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
            ],
            options={
                'unique_together': {('ville', 'annee', 'mois', 'jour')},
            },
        ),
    ]
