# Generated by Django 5.2.12 on 2026-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(help_text='Code de la région', max_length=5)),
                ('region', models.CharField(max_length=100)),
                ('dep', models.CharField(help_text='Code du département (ex: 75, 2A)', max_length=5, unique=True)),
                ('departement', models.CharField(max_length=100)),
                ('pop', models.IntegerField(verbose_name='Population municipale (PMUN)')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donnée Population',
                'verbose_name_plural': 'Données Population',
                'ordering': ['dep'],
            },
        ),
    ]
