# Generated by Django 5.2.12 on 2026-03-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteoarchive',
            old_name='ville',
            new_name='dep',
        ),
        migrations.AlterUniqueTogether(
            name='meteoarchive',
            unique_together={('dep', 'annee', 'mois', 'jour')},
        ),
    ]
