# Generated by Django 5.2.12 on 2026-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='reg',
            field=models.CharField(max_length=5),
        ),
    ]
